name: Deploy on Prod

on:
  push:
    branches: [ "main" ]

jobs:
  env:
    uses: ./.github/workflows/build-env.yaml

  build:
    needs: env
    runs-on: ubuntu-latest
    steps:
      - name: Download env artifact
        uses: actions/download-artifact@v4
        with:
          name: env

      - name: Import env
        shell: bash
        run: |
          while read env; do
            echo $env >> $GITHUB_ENV
          done <<< $(cat .env)

      - uses: actions/checkout@v4

      - name: Build the Docker image
        run: |
          touch environment.d
          echo "POSTGRES_CONNECTION_URI=${{ secrets.POSTGRES_CONNECTION_URI }}" >> environment.d
          echo "RIOT_TOKEN=${{ secrets.RIOT_TOKEN }}" >> environment.d
          echo "ORIGIN=${{ secrets.ORIGIN }}" >> environment.d
          echo "JWT_SECRET_KEY=${{ secrets.JWT_SECRET_KEY }}" >> environment.d
          echo "PROVIDER_ID=${{ secrets.PROVIDER_ID }}" >> environment.d
          docker build . --file Dockerfile --tag ${{ env.APP }}:latest
          docker tag ${{ env.APP }}:latest lblcs/${{ env.APP }}:latest
          docker tag ${{ env.APP }}:latest lblcs/${{ env.APP }}:${{ env.VERSION }}

      - name: Push Docker Image
        run: |
          echo ${{ secrets.DOCKER_PAT }} | docker login -u ${{ secrets.DOCKER_USERNAME }} --password-stdin
          docker push lblcs/${{ env.APP }}:${{ env.VERSION }}
          docker push lblcs/${{ env.APP }}:latest
          docker logout

  deploy:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Download env artifact
        uses: actions/download-artifact@v4
        with:
          name: env

      - name: Import env
        shell: bash
        run: |
          while read env; do
            echo $env >> $GITHUB_ENV
          done <<< $( cat .env)

      - name: Execute docker compose on prod server
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          key: ${{ secrets.SSH_KEY }}
          script: |
            cd docker/lblcs
            docker-compose -f ${{ env.APP }}.yaml down
            docker-compose -f ${{ env.APP }}.yaml pull
            docker-compose -f ${{ env.APP }}.yaml up -d